services:
  mailhog:
    image: ghcr.io/thorsten-l/mailhog:latest
    container_name: mailhog
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      - TZ=Europe/Berlin
    healthcheck:
      test: curl -s --fail http://localhost:8025/ > /dev/null || exit 1
      interval: 10s
      timeout: 30s
      retries: 3
